const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const header=$('.site-header');const progress=$('#scrollProgress');
window.addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>40);const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${h?scrollY/h*100:0}%`;updateNav()}, {passive:true});
const drawer=$('#mobileDrawer');$('#menuBtn')?.addEventListener('click',()=>{drawer.classList.add('open');drawer.setAttribute('aria-hidden','false')});$('#closeMenu')?.addEventListener('click',closeDrawer);$$('.mobile-drawer a').forEach(a=>a.addEventListener('click',closeDrawer));function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
const slides=$$('.hero-slide');let slideIndex=0;setInterval(()=>{slides[slideIndex].classList.remove('active');slideIndex=(slideIndex+1)%slides.length;slides[slideIndex].classList.add('active')},6500);
const search=$('#destinationSearch'), grid=$('#destinationGrid'), empty=$('#destinationEmpty');search?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();let count=0;$$('.destination-card',grid).forEach(card=>{const show=!q||card.dataset.search.includes(q);card.style.display=show?'block':'none';if(show)count++});empty.style.display=count?'none':'block'});
$$('[data-destination]').forEach(btn=>btn.addEventListener('click',()=>{const d=btn.dataset.destination;const select=$('#destination');if(select){select.value=d;}}));
const form=$('#bookingForm');form?.addEventListener('submit',e=>{e.preventDefault();const name=$('#name').value.trim();const dest=$('#destination').value||'Not selected';const date=$('#date').value||'Flexible';const travellers=$('#travellers').value||'Not specified';const service=$('#service').value;const msg=$('#message').value.trim()||'No extra details yet.';const text=`Hello Adventure Safaris East Africa!%0A%0AI'd like to plan a journey.%0A%0A*Name:* ${encodeURIComponent(name)}%0A*Destination:* ${encodeURIComponent(dest)}%0A*Travel date:* ${encodeURIComponent(date)}%0A*Travellers:* ${encodeURIComponent(travellers)}%0A*Service:* ${encodeURIComponent(service)}%0A*Details:* ${encodeURIComponent(msg)}%0A%0APlease advise me on the next steps.`;window.open(`https://wa.me/256761890792?text=${text}`,'_blank','noopener')});
$('#year').textContent=new Date().getFullYear();
function updateNav(){const ids=['home','destinations','services','contact'];const links=$$('.mobile-bottom-nav a');const y=scrollY+innerHeight*.35;let active='home';ids.forEach(id=>{const el=document.getElementById(id);if(el&&el.offsetTop<=y)active=id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${active}`))}updateNav();
$$('.destination-card,.service-card').forEach(card=>{card.addEventListener('pointermove',e=>{if(innerWidth<900)return;const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(700px) rotateX(${y*-2.5}deg) rotateY(${x*2.5}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
